# Generated by Django 4.1.3 on 2022-11-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videohistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videohistory',
            name='video',
        ),
        migrations.AddField(
            model_name='videohistory',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videohistory',
            name='video',
            field=models.ManyToManyField(related_name='history', to='contents.videocontent', verbose_name='Watch Video'),
        ),
    ]
