# Generated by Django 4.1.1 on 2022-11-11 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_remove_videohistory_user_remove_videohistory_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchLater', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
                ('video', models.ManyToManyField(related_name='watchLater', to='contents.videocontent', verbose_name='Watch Video')),
            ],
            options={
                'verbose_name': 'Watch Later',
                'verbose_name_plural': 'Watch Later',
            },
        ),
    ]
