# Generated by Django 4.1.1 on 2022-11-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_watchlater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlater',
            old_name='video',
            new_name='videos',
        ),
    ]
