# Generated by Django 4.1.1 on 2022-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_userreact_alter_playlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='react',
            field=models.ManyToManyField(default='N', related_name='content', to='contents.userreact', verbose_name='User Reaction'),
        ),
    ]
