# Generated by Django 4.1.1 on 2022-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_videocontent_react'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='react',
        ),
        migrations.AddField(
            model_name='userreact',
            name='content',
            field=models.ManyToManyField(related_name='react', to='contents.videocontent', verbose_name='Select Content'),
        ),
    ]
