# Generated by Django 4.1.1 on 2022-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_remove_videocontent_react_userreact_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreact',
            name='react',
            field=models.CharField(choices=[('LO', 'Love'), ('AN', 'Angry'), ('LI', 'Like'), ('DI', 'Dislike'), ('NO', 'NO React')], max_length=2),
        ),
    ]
