# Generated by Django 4.1.1 on 2022-10-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channelLogo',
            field=models.ImageField(default='channelLogoDefault.jpg', help_text='Upload A Picture(Channel Logo).', upload_to='mediafilles/coverPicture/', verbose_name='Channel Logo'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(max_length=800, verbose_name='About This Channel.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='coverPicture',
            field=models.ImageField(default='defaultCoverPicture.jpg', help_text='Upload A Cover Picture.', upload_to='mediafilles/coverPicture/', verbose_name='Cover Picture'),
        ),
    ]
