# Generated by Django 4.1.1 on 2022-09-29 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channelanalytics', '0002_alter_channel_options_alter_channel_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, related_name='sususer', to=settings.AUTH_USER_MODEL, verbose_name='Subscriber Email'),
        ),
    ]
