# Generated by Django 4.1.1 on 2022-09-29 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channelanalytics', '0003_remove_channel_subscriber_channel_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='maincontent',
            field=models.FileField(blank=True, null=True, upload_to='mediafilles/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Channel Name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='sususer', to=settings.AUTH_USER_MODEL, verbose_name='Subscriber Email'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
