# Generated by Django 4.1.1 on 2022-09-30 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelanalytics', '0005_alter_channel_maincontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='maincontent',
            field=models.FileField(blank=True, help_text='Upload a Short Video.', null=True, upload_to='mediafilles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
